Repository tempesta-tech/mariadb, pull requests merged in 2018-07, with the labels that each got.

#514 MDEV-16252: MINIMAL binlog_row_image does not work for versioned tables
  mysql-test/suite/versioning/r/rpl.result
  mysql-test/suite/versioning/t/rpl.test
  sql/sql_update.cc
Labels: bug, task

#518 MDEV-16734: LOAD DATA and system_versioning_modify_history
  mysql-test/suite/versioning/r/sysvars.result
  mysql-test/suite/versioning/t/sysvars.test
  sql/sql_class.cc
Labels: bug

#522 MDEV-16764: Crash on delete from sql-versioned table with update trigger
  mysql-test/suite/versioning/r/delete.result
  mysql-test/suite/versioning/t/delete.test
  sql/sql_base.cc
  sql/sql_update.cc
Labels: bug

#523 MDEV-16355 Add option for mysqldump to read data as of specific timestamp from system-versioned tables
  client/client_priv.h
  client/mysqldump.c
  mysql-test/suite/versioning/r/data.result
  mysql-test/suite/versioning/t/data.test
Labels: task
